global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.163.com:25'
  smtp_from: 'smtpusername@163.com'
  smtp_auth_username: 'smtpusername@163.com'
  smtp_auth_password: 'XOXSGXFHXTOXLUXR'
  smtp_require_tls: false

templates:
  - 'template/alert_mail.tmpl'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'byemail'

receivers:
- name: 'byemail'
  email_configs:
  - to: 'rcvusername@sina.com'
    html: '{{ template "demo.html" . }}'
    headers: { Subject: "[!WARN!] Vagrant Demos System Alarm Notification"}
    send_resolved: true
  webhook_configs:
  - url: 'http://127.0.0.1:18000'
    send_resolved: true
  - url: 'http://MASTER:18090'
    send_resolved: true

inhibit_rules:
  - source_match:
     severity: 'critical'
    target_match:
     severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

