global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - "alerting_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets:
      - 'prometheus:9090'

  - job_name: 'node'
    static_configs:
    - targets:
      - 'prometheus:9100'
      - 'LAMP:9100'
      - 'alertmanager:9100'

  - job_name: 'alertmanager'
    static_configs:
    - targets:
      - 'alertmanager:9093'

  - job_name: 'apache'
    static_configs:
    - targets:
      - 'LAMP:9117'

  - job_name: 'mysql'
    static_configs:
    - targets:
      - 'LAMP:9104'

  - job_name: 'blackbox-icmp'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
         - alertmanager
         - LAMP
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

  - job_name: "blackbox-http"
    metrics_path: "/probe"
    params:
      module: [ "http_2xx" ]
    relabel_configs:
      - source_labels: [ "__address__" ]
        target_label: "__param_target"
      - source_labels: [ "__param_target" ]
        target_label: "instance"
      - target_label: "__address__"
        replacement: "localhost:9115"
    static_configs:
      - targets: 
         - http://LAMP/


  - job_name: "blackbox_tcp"
    metrics_path: "/probe"
    params:
      module: ["tcp_connect"]
    static_configs:
      - targets:
        - LAMP:80
    relabel_configs:
      - source_labels: ["__address__"]
        target_label: "__param_target"
      - source_labels: ["__param_target"]
        target_label: "instance"
      - target_label: "__address__"
        replacement: "localhost:9115"

